import Foundation

/// Exact, build-time verified NetEase Cloud Music album destinations.
///
/// NetEase album IDs are opaque. Keeping the reviewed mapping in the app avoids
/// fuzzy search at tap time and lets the installed app open the requested album
/// through the same `orpheus://album/<id>` route used by NetEase's mobile site.
public enum NetEaseCatalog {
    private struct CuratedCatalog: Decodable {
        let albums: [String: CuratedAlbum]
    }

    private struct CuratedAlbum: Decodable {
        let albumId: String
        let artist: String
        let title: String
        let year: Int?
        let method: String
    }

    private static let curatedCatalog: CuratedCatalog? = {
        try? DataLoader.decode("netease", as: CuratedCatalog.self, bundle: .module)
    }()

    public static var curatedCount: Int { curatedCatalog?.albums.count ?? 0 }

    public static func albumID(for album: Album) -> String? {
        guard let id = curatedCatalog?.albums[album.id]?.albumId,
              !id.isEmpty,
              id.allSatisfy(\.isNumber) else { return nil }
        return id
    }

    /// Official mobile album page. It works without the app and provides
    /// NetEase's own app-opening affordance, making it the reliable fallback.
    public static func webURL(for album: Album) -> URL? {
        guard let id = albumID(for: album) else { return nil }
        var components = URLComponents()
        components.scheme = "https"
        components.host = "y.music.163.com"
        components.path = "/m/album"
        components.queryItems = [URLQueryItem(name: "id", value: id)]
        return components.url
    }

    /// NetEase's supported album route, as generated by its own mobile client
    /// code. Unlike the former search route, it identifies a real destination.
    public static func appURL(for album: Album) -> URL? {
        guard let id = albumID(for: album) else { return nil }
        return URL(string: "orpheus://album/\(id)")
    }
}
